### ISSUE TITLE
npm package dependence problem.

### ISSUE THREAD

**Issue by shrinktofit** [cocos-creator/engine-3d#690]
While execute ``npm install``, the package "uglifyjs" won't be installed and while execute ``npm run build``, the cmd will prompt that "uglifyjs is not a executable".

**Comment by shrinktofit** [comment]
I test this again and the problem disappears strangely.

**Comment by dabingnn** [comment]
So, let us just close this issue, and if we have similar problem again, we can double check it.

**Comment by YunHsiao** [comment]
the uglify-js is all we need. this particular issue sounds like a network connection problem during `npm install`.
