### ISSUE TITLE
数学库是否保留create?

### ISSUE THREAD

**Issue by YunHsiao** [cocos-creator/engine-3d#696]
~~虽然对vector来说zero表意更清晰一些, 但考虑到包括quaternion, color, mat, box, sphere等等都采用create的convention, 并且对这些所有的类全部改成zero并不怎么make sense, 建议还是改回create, 保持统一的convention更为重要.~~

这里主要想提的是保留一个统一的create接口感觉还是比较顺手, 比如在作为临时变量使用的时候.

目前在使用中, 要新建一个变量, 还得先考虑这到底是个向量还是四元数, 再决定写zero还是create, 实际体验其实是不太好的.

下一步可以考虑数学库非静态方法的建设, 还是像上次讨论的一样, 引擎层可以保持不使用, 留给客户端作为一个更加顺手的API. 并且可以提供类似unity的静态成员变量(Vector3.zero)供直接使用.

具体那些方法到底是以静态成员变量形式还是用于创建变量功能的函数的形式, 可以再开一个issue了.

**Comment by shrinktofit** [comment]
我认为应该依然保留Vector的zero方法，并且移除这些数学量的所有create方法：
* Quaternion、Matrix使用identity;
* Color使用black;
* Box、Sphere使用unit。
实际上用户（至少我是这样）在使用quaternion、maxtrix、box的时候**会去想，或者查文档来弄明白这个create到底是在干什么**？
例如：
* quat.create是帮我创建了一个值全为0的四元数，还是一个(0,0,0,1)的四元数；
* mat*.create是帮我创建了一个值全为0的矩阵（以此来求多个矩阵的和），还是一个Identity矩阵。
* box.create是帮我创建了一个max为(-Infinity, -Infinity, -Infinity)、min为(Infinity, Infinity, Infinity)的包围盒（这样的包围盒可以用来，比如，生成包围多个点的一个包围盒），还是中心在原点，边长为(1, 1, 1)的单位包围盒（暂时没想到用处）；
* color.create是帮我创建了一个全黑颜色还是全白颜色。

**Comment by YunHsiao** [comment]
也有道理, 但如果真的不保留create的话,还是常有使用起来不顺手的地方, 比如时常地需要创建一个临时vector, 我并不关心它里面的值是多少, 只是拿来做临时变量, 这时使用哪个接口的问题会变得更加头疼; 另外如果是有针对性地创建一个变量的话, 我一般会直接用new来指定我要的数值; 而在API层面, 感觉以`静态成员变量`的形式给出如color4.black, color4.white, color4.magenta, color4.cyan等要更合理一些.

**Comment by JoneLau** [comment]
我觉得大多数地方保留 zero 还是比较方便用户去理解的，create 对于用户理解来说我觉得跟 new 没什么区别，其实完全可以参照 unity 的类似用法，例如一个 matrix，如果是一个 0 矩阵，可以用 Matrix.zero，如果是方阵，可以用 Matrix.identity 这样，color 也是可以有 color.black, color.white, color.grey 这样提供给用户

**Comment by dabingnn** [comment]
我最近想到一个用法，用create加默认参数来完成
`vec2.create(x = 0, y = 0 )`
`vec3.create(x = 0, y = 0, z = 0 )`
`vec4.create(x = 0, y = 0, z = 0, w = 1 )`
`quat.create(x = 0, y = 0, z= 0, w = 1)`
`mat2.create(...)` 默认参数正好是一个identity
如果用户自行传入参数，那就用用户的参数

**Comment by shrinktofit** [comment]
@dabingnn 
``create``的宗旨应该就是不需要参数快速创建一个自然的、值为**0**或者**1**的对象。你这个方法不如直接用``new``来创建。

**Comment by dabingnn** [comment]
不用new的原因是，因为new是关键字，create不是，理论上zero这些算是utils，只是create的特殊用例而已。

**Comment by dabingnn** [comment]
之前的数学库是参考的 https://github.com/toji/gl-matrix里面的写法，对其综合分析发现，
1. 函数定义混乱，new，zero，create等掺杂其中
2. 写法让代码长度变得更长
3. 写法和现有的主流引擎包括C++和JS引擎，差异很大，和cocos2d-x. creator差异也很大
对于数学库将进行以下的调整：
1. 所有的数据的创建走的是create函数：vecX.create, quat.create, matX.create(). create函数带有默认参数，默认情况下，vec2(0,0), vec3(0, 0, 0), vec4(0,0,0,1), quat(0,0,0,1)(identity), matX(identity)
2. 提供utils类似的函数
* zero()表示全0.不管是vec，quat，mat，只要用了zero，就意味着所有的数据都是0。
* quat, mat2, mat3, mat4提供identity函数

暂时调整如下：
对于非静态的数学库版本，将会重点调研目前市场的引擎的通用做法，并且结合目前creator和cocos2d-x用户的使用习惯，设计一版非静态数学库，这个任务将在后续完成 https://github.com/cocos-creator/engine-3d/issues/597
